vim.cmd [[ hi clear ]]
vim.cmd [[ syntax reset ]]
vim.cmd [[ let g:colors_name = "hybrid" ]]
vim.cmd [[ set background=dark ]]
vim.cmd [[ set t_Co=256 ]]
vim.cmd [[ hi Normal guifg=#b7bcb9 ctermbg=NONE guibg=#161718 gui=NONE ]]

vim.cmd [[ hi DiffText guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi ErrorMsg guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi WarningMsg guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi PreProc guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi Exception guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi Error guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi DiffDelete guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi GitGutterDelete guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi GitGutterChangeDelete guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi cssIdentifier guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi cssImportant guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi Type guifg=#b7bcb9 guibg=NONE gui=BOLD ]]
vim.cmd [[ hi Identifier guifg=#b7bcb9 guibg=NONE ]]
vim.cmd [[ hi PMenuSel guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi Constant guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi Repeat guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi DiffAdd guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi GitGutterAdd guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi cssIncludeKeyword guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi Keyword guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi IncSearch guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Title guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi PreCondit guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Debug guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi SpecialChar guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Conditional guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Todo guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Special guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Label guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Delimiter guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Number guifg=#7fbeb3 guibg=NONE ]]
vim.cmd [[ hi CursorLineNR guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Define guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi MoreMsg guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Tag guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi String guifg=#b3be5a guibg=NONE ]]
vim.cmd [[ hi MatchParen guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Macro guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi DiffChange guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi GitGutterChange guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi cssColor guifg=#959d98 guibg=NONE ]]
vim.cmd [[ hi Function guifg=#6d90b0 guibg=NONE ]]
vim.cmd [[ hi Directory guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi markdownLinkText guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi javaScriptBoolean guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi Include guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi Storage guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi cssClassName guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi cssClassNameDot guifg=#a07eab guibg=NONE ]]
vim.cmd [[ hi Statement guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi Operator guifg=#e3b55e guibg=NONE ]]
vim.cmd [[ hi cssAttr guifg=#e3b55e guibg=NONE ]]


vim.cmd [[ hi Pmenu guifg=#b7bcb9 guibg=#35363c ]]
vim.cmd [[ hi SignColumn guibg=#161718 ]]
vim.cmd [[ hi Title guifg=#b7bcb9 ]]
vim.cmd [[ hi LineNr guifg=#505653 guibg=#161718 ]]
vim.cmd [[ hi NonText guifg=#b3be5a guibg=#161718 ]]
vim.cmd [[ hi Comment guifg=#b3be5a gui=NONE ]]
vim.cmd [[ hi SpecialComment guifg=#b3be5a gui=italic guibg=NONE ]]
vim.cmd [[ hi CursorLine guibg=#35363c ]]
vim.cmd [[ hi TabLineFill gui=NONE guibg=#35363c ]]
vim.cmd [[ hi TabLine guifg=#505653 guibg=#35363c gui=NONE ]]
vim.cmd [[ hi StatusLine gui=bold guibg=#35363c guifg=#b7bcb9 ]]
vim.cmd [[ hi StatusLineNC gui=NONE guibg=#161718 guifg=#b7bcb9 ]]
vim.cmd [[ hi Search guibg=#b3be5a guifg=#b7bcb9 ]]
vim.cmd [[ hi VertSplit gui=NONE guifg=#35363c guibg=NONE ]]
vim.cmd [[ hi Visual gui=NONE guibg=#35363c ]]


-- Highlight not underline for illuminate.nvim
vim.cmd [[ hi! IlluminatedWordText  guibg=#2a2e33 gui=NONE]]
vim.cmd [[ hi! IlluminatedWordRead  guibg=#2a2e33 gui=NONE]]
vim.cmd [[ hi! IlluminatedWordWrite guibg=#2a2e33 gui=NONE]]

vim.cmd [[ hi! DiagnosticError guifg=#b74d50 ]]
